# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
NAME = "saltmaster.vagrant.local"
IP = "172.16.13.100"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "ubuntu/trusty64"

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"

    config.vm.hostname = NAME

    # Hostname
    config.vm.network "private_network", ip: IP

    # The specs of our production machines
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
        v.customize ['modifyvm', :id, '--name', 'salt-master']
        # v.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    end

    config.vm.synced_folder "srv/", "/srv/salt"
    config.vm.provision "shell", path: "../setup.sh"
end
